org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
android.ndkVersion=28.0.12404108
android.suppressUnsupportedCompileSdk=36
firebase.crashlytics.nativeSymbolUploadEnabled=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
