// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWhs8oIS_6yebct45c15mzkKE10y94FFY',
    appId: '1:1045027803262:web:f8abf0cac486227239882f',
    messagingSenderId: '1045027803262',
    projectId: 'iroyal-91744',
    authDomain: 'iroyal-91744.firebaseapp.com',
    storageBucket: 'iroyal-91744.appspot.com',
    measurementId: 'G-TEESMM46DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0kzGTB7toppqEDg7j1SSFEV26ORvh0k',
    appId: '1:1045027803262:android:d51c5193158dd78a39882f',
    messagingSenderId: '1045027803262',
    projectId: 'iroyal-91744',
    storageBucket: 'iroyal-91744.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEcxUnZwOuTNAUJjWXfmSK7JdjnPUL4qU',
    appId: '1:1045027803262:ios:d43ab58f13e9673539882f',
    messagingSenderId: '1045027803262',
    projectId: 'iroyal-91744',
    storageBucket: 'iroyal-91744.appspot.com',
    iosBundleId: 'com.example.iroyal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEcxUnZwOuTNAUJjWXfmSK7JdjnPUL4qU',
    appId: '1:1045027803262:ios:d43ab58f13e9673539882f',
    messagingSenderId: '1045027803262',
    projectId: 'iroyal-91744',
    storageBucket: 'iroyal-91744.appspot.com',
    iosBundleId: 'com.example.iroyal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWhs8oIS_6yebct45c15mzkKE10y94FFY',
    appId: '1:1045027803262:web:f03a8895c267c5a339882f',
    messagingSenderId: '1045027803262',
    projectId: 'iroyal-91744',
    authDomain: 'iroyal-91744.firebaseapp.com',
    storageBucket: 'iroyal-91744.appspot.com',
    measurementId: 'G-Y1S0P5E8MB',
  );
}
