// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWhs8oIS_6yebct45c15mzkKE10y94FFY',
    appId: '1:1045027803262:web:f8abf0cac486227239882f',
    messagingSenderId: '1045027803262',
    projectId: 'iroyal-91744',
    authDomain: 'iroyal-91744.firebaseapp.com',
    storageBucket: 'iroyal-91744.appspot.com',
    measurementId: 'G-TEESMM46DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTXlGpvnUgLFDv3FJDFnaDFHSWzBNeTvA',
    appId: '1:830784728566:android:47c298d97d4b5504bfebd7',
    messagingSenderId: '830784728566',
    projectId: 'iroyal-14dea',
    storageBucket: 'iroyal-14dea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd_69P7bWeHbFH33VB-YVAOvSBKpzBSLc',
    appId: '1:830784728566:ios:6be2f8f02c0a8204bfebd7',
    messagingSenderId: '830784728566',
    projectId: 'iroyal-14dea',
    storageBucket: 'iroyal-14dea.firebasestorage.app',
    iosBundleId: 'com.myroyal',
  );

}